### ISSUE TITLE
[Issue] Does not save settings after reboot

### ISSUE THREAD

**Issue by FLDataTeK** [bpopp/Octoprint-Cura-Superslicer-Uploader#2]
I configured the app and everything works just fine but after I reboot when the machine comes back up it ask for me to put all the settings back in. So it looks like it is not retaining the settings. 

This is a Windows 10 x64 PC.

**Comment by bpopp** [comment]
Should be fixed in 1.2. I think it was caused by settings not getting upgraded correctly from one version to the next. Please let me know if you see this again.

**Comment by FLDataTeK** [comment]
Loaded up 1.2 and now its not loading up on reboot.. Also if I manually launch the app it loads but as soon as I put my mouse over the icon to set up the settings the icon disappears and the app dies.

I have tried running it in admin mode, and with compatibility mode with Windows 7 and 8.1. I also completely removed the app from the PC and reinstalled and the same thing.

**Comment by bpopp** [comment]
@FLDataTeK , please try to load 1.2.1. It fixes a bug with loading settings that was likely causing the crash. I suspect your settings will be empty initially, but should hopefully get saved and upgraded correctly moving forward.

**Comment by FLDataTeK** [comment]
Loaded up the new 1.2.1 version and it loads fine but was still not saving after reboot so I started looking around a bit and think I have found what is causing the problem. 

In the user.conf file I changed 
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <OctoUploader.Properties.Settings>
            <setting name="ServerAddress" serializeAs="String">
                <value />
            </setting>
            <setting name="APIKey" serializeAs="String">
                <value />
            </setting>
            <setting name="DeleteOnUpload" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="WatchLocation" serializeAs="String">
                <value>C:\Octopi</value>
            </setting>
            <setting name="AutoStart" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="RelaunchOnStartup" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CallUpgrade" serializeAs="String">
                <value>False</value>
            </setting>
        </OctoUploader.Properties.Settings>
    </userSettings>
</configuration>

```
To the following and now it not only works but it also saves the settings between reboots as well . 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <OctoUploader.Properties.Settings>
            <setting name="ServerAddress" serializeAs="String">
                <value>http://10.10.0.32</value>
            </setting>
            <setting name="APIKey" serializeAs="String">
                <value>2D9C15CXXXXXXXXXXXXXXX</value>
            </setting>
            <setting name="DeleteOnUpload" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="WatchLocation" serializeAs="String">
                <value>C:\Octopi</value>
            </setting>
            <setting name="AutoStart" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="RelaunchOnStartup" serializeAs="String">
                <value>True</value>
            </setting>
            <setting name="CallUpgrade" serializeAs="String">
                <value>False</value>
            </setting>
        </OctoUploader.Properties.Settings>
    </userSettings>
</configuration>

```
Most notibily I changed these that didn't look the same as the others so the syntax may be wrong and it doesn't look like the statement is opened or closed correctly. (this is also present in the octouploader.exe.config file in the programs directory. 

```
  <setting name="ServerAddress" serializeAs="String">
                <value />
            </setting>
            <setting name="APIKey" serializeAs="String">
                <value />
```


Hope this helps.. And thank you for all your work... If you need me to test further please let me know. 

-Jeremy

**Comment by FLDataTeK** [comment]
@bpopp I just wanted to tag you so the info I found doesn't get overlooked. After I manually modified that file and made the corrections I have had zero issues even after multiple reboots.
